[package]
name = "terra-tests"
version.workspace = true
edition.workspace = true
publish = false

[dependencies]
terra-core = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
