[package]
name = "terra-core"
version = "0.0.1"
edition = "2021"

[dependencies]
thiserror = "1.0.40"
anyhow = "1.0.70"
rust-crypto = "0.2.36"
aes-stream = { path = "../aes-stream" }
byteorder = "1.4.3"
bit_reverse = "0.1.8"
serde = { version = "1.0.149", features = ["derive"] }
serde_json = "1.0.95"
serde_repr = "0.1.12"
serde-big-array = "0.5.1"
chrono = "0.4.24"
dirs-next = "2.0.0"
