[package]
name = "terra-res"
version = "0.0.1"
edition = "2021"

[dependencies]
terra-core = { path = "../terra-core", features = ["serialize"] }
anyhow = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
rlua = "0.19.7"
regex = "1.9.5"
scraper = "0.17.1"
reqwest = { version = "0.11.20", features = ["blocking", "json"] }
fs_extra = "1.3.0"
image = { workspace = true }
itertools = "0.11.0"
