[package]
name = "terra-gui"
version = "0.0.1"
edition = "2021"

[dependencies]
terra-core = { path = "../terra-core" }

anyhow = "1.0.72"

once_cell = "1.18.0"
parking_lot = "0.12.1"
flume = "0.10.14"

rustc-hash = "1.1.0"

eframe = { version = "0.22.0", features = ["persistence", "ron"] }
egui = { version = "0.22.0", features = ["color-hex"] }
catppuccin-egui = "3.0.0"
egui_dock = { version = "0.6.3", features = ["serde"] }

image = { version = "0.24.6", features = ["png"] }

rfd = "0.11.4"
open = "5.0.0"

serde = { version = "1.0.177", features = ["derive"] }
